project_name: PyTorchSpiking
pkg_name: pytorch_spiking
repo_name: nengo/pytorch-spiking

description: Spiking neuron integration for PyTorch
copyright_start: 2020

license_rst: {}

contributing_rst: {}

contributors_rst: {}

manifest_in: {}

setup_cfg:
  pytest:
    xfail_strict: True
  pylint:
    known_third_party:
      - torch

docs_conf_py:
  nengo_logo: ""
  extensions:
    - nengo_sphinx_theme.ext.autoautosummary
  analytics_id: UA-41658423-2
  doctest_setup:
    - import numpy as np
    - import torch
  autoautosummary_change_modules:
    pytorch_spiking:
      - pytorch_spiking.modules.SpikingActivation
      - pytorch_spiking.modules.Lowpass
      - pytorch_spiking.modules.TemporalAvgPool

ci_scripts:
  - template: static
    codespell_ignore_words:
      - hist
  - template: test
    coverage: true
    pip_install:
      - $PYTORCH_VERSION
      - $NUMPY_VERSION
      - nengo
  - template: docs
    pip_install:
      - $PYTORCH_VERSION
      - $NUMPY_VERSION
  - template: examples
    pip_install:
      - $PYTORCH_VERSION
      - $NUMPY_VERSION
  - template: remote-script
    remote_script: docs
    output_name: remote-docs
    host: azure-docs
    travis_var_key: 2895d60e3414
  - template: remote-script
    remote_script: examples
    output_name: remote-examples
    host: azure-examples
    travis_var_key: 2895d60e3414
  - template: deploy

travis_yml:
  python: 3.8
  global_vars:
    NUMPY_VERSION: numpy>=1.16.0
    PYTORCH_VERSION: torch>=1.0.0
  jobs:
    - stage: basic
      script: static
    - script: test
    - script: test
      env:
        PYTORCH_VERSION: torch==1.0.0
        NUMPY_VERSION: numpy==1.16.0
      python: 3.6
    - stage: advanced
      script: remote-docs
      env:
        GPU_NUM: 0
    - script: remote-examples
      env:
        GPU_NUM: 0
  pypi_user: drasmuss
  deploy_dists:
    - sdist
    - bdist_wheel
  slack_notifications: "m+yuPdTXYDo0pvPVp2LE2GE50llIpiroyHf/li3SNAnW3K2z3kUbIx0jCINr\
    7okCKpNKBKIifCc25NDUGBeJ+r1Ar7XR/PFCs4J2Kaksl95ei+ORpXxxScrBoi7AxM6dQchPuc62mxiD\
    c8E+gSS0WSP0tKjZTn1IypZOR6nDj7qqsQFU1r59rMpYY/Crk2QyylcqXgxgKHtIivqZkYNdwCSCobhQ\
    SrAINeUPXL5kbe8NzhgFB32vNC3UQoikNhNiYpLb3uApPCQeaQ0uVJbCiFktJVH7v2SVHd/BzTfmwE2G\
    xRFVwHZP39wxlm+Qvx9+2Nr1lfwEAgSzMe10zCo7/3nlhLPfLGHfGKJbMTAJGgsY49A0vJ4v6O2BbUyH\
    T+y2WlCS1/B8q2b07nYq+5AJP0eZknU2c/QtuP/a2Hlv00Hasi5xyS0Jd9AjPVIjXHQArjISoGnFkRxG\
    ZbaecDQURkpugZfUZT6IVuwIwven4HSugoJ7SzbSieTF4mYCLxptaOaZq4GIoD+ICEAZeiwFm1NPxnJd\
    mOFY+JD3Qh3oAglVDDSp2hqRFMi+cgdxOr+UgKwB20W53EsYRpQiOqx3zZ/K9vP7jCpe6rXti5AtWpOU\
    LgIil9+0FCxD7gKP/KrkSN1g+OEhdNgXKzqPJS1RE4VGyu9RqvpbSaj1gk/zp/8="

codecov_yml:
  abs_target: 100%

setup_py:
  include_package_data: True
  install_req:
    - numpy>=1.16.0
    - torch>=1.0.0
  docs_req:
    - jupyter>=1.0.0
    - matplotlib>=2.0.0
    - nbsphinx>=0.3.5
    - nengo-sphinx-theme>=1.2.1
    - numpydoc>=0.6.0
    - sphinx>=3.0.0
    - torchvision>=0.7.0
  tests_req:
    - pylint>=1.9.2
    - pytest>=3.6.0
    - pytest-allclose>=1.0.0
    - pytest-cov>=2.6.0
    - pytest-rng>=1.0.0
    - pytest-xdist>=1.16.0
  classifiers:
      - "Development Status :: 3 - Alpha"
      - "Intended Audience :: Science/Research"
      - "License :: Free for non-commercial use"
      - "Operating System :: Microsoft :: Windows"
      - "Operating System :: POSIX :: Linux"
      - "Programming Language :: Python"
      - "Programming Language :: Python :: 3.6"
      - "Programming Language :: Python :: 3.7"
      - "Programming Language :: Python :: 3.8"
      - "Topic :: Scientific/Engineering"
      - "Topic :: Scientific/Engineering :: Artificial Intelligence"

pyproject_toml: {}

pre_commit_config_yaml: {}
