project_name: PyTorchSpiking
pkg_name: pytorch_spiking
repo_name: nengo/pytorch-spiking

description: Spiking neuron integration for PyTorch
copyright_start: 2020
license: abr-free
main_branch: main

license_rst: {}

contributing_rst: {}

contributors_rst: {}

manifest_in: {}

setup_cfg:
  pytest:
    xfail_strict: True
  pylint:
    disable:
      - not-callable # https://github.com/pytorch/pytorch/issues/24807
    known_third_party:
      - torch
  codespell:
    ignore_words:
      - hist

docs_conf_py:
  nengo_logo: ""
  extensions:
    - nengo_sphinx_theme.ext.autoautosummary
  doctest_setup:
    - import numpy as np
    - import torch
  autoautosummary_change_modules:
    pytorch_spiking:
      - pytorch_spiking.modules.SpikingActivation
      - pytorch_spiking.modules.Lowpass
      - pytorch_spiking.modules.TemporalAvgPool

ci_scripts:
  - template: static
  - template: test
    coverage: true
    pip_install:
      - $PYTORCH_VERSION
      - nengo[tests]
  - template: docs
    pip_install:
      - $PYTORCH_VERSION
  - template: examples
    pip_install:
      - $PYTORCH_VERSION
  - template: remote-script
    remote_script: docs
    output_name: remote-docs
    host: azure-docs
    azure_name: nengo-dl-docs
    azure_group: nengo-ci
    remote_vars:
      PYTORCH_VERSION: $PYTORCH_VERSION
    remote_setup:
      - micromamba install -y cudatoolkit=10.2
  - template: remote-script
    remote_script: examples
    output_name: remote-examples
    host: azure-examples
    azure_name: nengo-dl-examples
    azure_group: nengo-ci
    remote_vars:
      PYTORCH_VERSION: $PYTORCH_VERSION
    remote_setup:
      - micromamba install -y cudatoolkit=10.2
  - template: deploy
    wheel: true

setup_py:
  include_package_data: True
  install_req:
    - numpy>=1.16.0
    - torch>=1.0.0
  docs_req:
    - jupyter>=1.0.0
    - matplotlib>=2.0.0
    - nbsphinx>=0.3.5
    - nengo-sphinx-theme>=1.2.1
    - numpydoc>=0.6.0
    - sphinx>=3.0.0
    - torchvision>=0.7.0
  tests_req:
    - pylint>=1.9.2
    - pytest>=3.6.0
    - pytest-allclose>=1.0.0
    - pytest-cov>=2.6.0
    - pytest-rng>=1.0.0
    - pytest-xdist>=1.16.0
  classifiers:
    - "Development Status :: 3 - Alpha"
    - "Intended Audience :: Science/Research"
    - "Operating System :: Microsoft :: Windows"
    - "Operating System :: POSIX :: Linux"
    - "Programming Language :: Python"
    - "Programming Language :: Python :: 3.6"
    - "Programming Language :: Python :: 3.7"
    - "Programming Language :: Python :: 3.8"
    - "Topic :: Scientific/Engineering"
    - "Topic :: Scientific/Engineering :: Artificial Intelligence"

pyproject_toml: {}

pre_commit_config_yaml: {}
